name: Build nerc-ansible-conainter image ( using nerc-github-workflows )

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: nerc-project/nerc-github-workflows/.github/workflows/build-image.yaml@main

    with:
      image: ghcr.io/nerc-project/nerc-ansible-container
    secrets: inherit
